### ISSUE TITLE
Summary line is not correct

### ISSUE THREAD

**Issue by gard** [tazjin/terraform-provider-keycloak#13]
When provisioning a new client the summary line says:

`Plan: 2 to add, 0 to change, 0 to destroy.`

While only one change is listed:
`+ module.tcv2-configuration.keycloak_client.clearing-processor
    bearer_only:               "false"
`

**Comment by tazjin** [comment]
**that** is odd, considering that the summary code happens in Terraform itself 🤔 

I'll take a look once I'm off this train.

**Comment by tazjin** [comment]
This isn't really anything I can influence, probably an upstream bug in Terraform. Closing this issue and hoping it sorts itself out somewhere else!
