### ISSUE TITLE
terraform 0.10.0 appears to have broken provider loading

### ISSUE THREAD

**Issue by sharebear** [tazjin/terraform-provider-keycloak#16]
See output of terraform init

```
$ terraform init
Downloading modules...
Get: file:///Users/jshare/Source/<redacted>
Initializing provider plugins...
- Downloading plugin for provider "keycloak"...

Provider "keycloak" not available for installation.

A provider named "keycloak" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

It looks like the contents of `~/.terraformrc` are now ignored and we need to use the terraform.d folder structure.

I resolved this locally be performing the following two commands:

```
mkdir -p terraform.d/plugins/darwin_amd64
ln -s /Users/jshare/go/bin/terraform-provider-keycloak terraform.d/plugins/darwin_amd64/terraform-provider-keycloak
```

Not sure if that's the correct solution but either way the documentation needs to be updated to reflect this.

**Comment by tazjin** [comment]
Hmm, I was going to update the documentation with a reference to the [official docs](https://www.terraform.io/docs/plugins/basics.html#installing-a-plugin) but those still clearly refer to `~/.terraformrc`. 

Googling a bit [it seems like](https://github.com/hashicorp/terraform/issues/15705#issuecomment-320342792) this was actually supposed to still work after the latest release. Gonna figure out if there's a better official doc to refer to for the _new_ way ...

**Comment by sharebear** [comment]
FYI: 0.10.3 fixed loading from `~/.terraformrc`, confused the hell out of me for about 30 mins now as my `~/.terraformrc` had a reference to an older binary than I now had in `~/.terraform.d/plugins/`
