### ISSUE TITLE
`Error asking for user input` with newer builds of plugin

### ISSUE THREAD

**Issue by sharebear** [tazjin/terraform-provider-keycloak#17]
Performing a `go get github.com/tazjin/terraform-provider-keycloak` in a clean gopath today results in a binary that doesn't work. When running `terraform plan` we get the following output.

```
Error asking for user input: 1 error(s) occurred:

* module.REDACTED.provider.keycloak: dial unix /var/folders/_d/hlc2psr11dx044w67ddwt8yc0000gn/T/plugin249198428|netrpc: connect: no such file or directory
```

Providing the KEYCLOAK_CLIENT_SECRET env var doesn't appear to avoid this error.

I'm guessing that the problem is probably upstream in terraform but still, if not publishing binary releases this project should do whatever is necessary to achieve a reproducible build.

**Comment by sharebear** [comment]
FYI, my working $GOPATH/src/github.com/hashicorp/terraform  e50a57bcb7f3e7a0469f5b9b030df9074bb10bfa

My failing version is at 5c8ff928babf15ed929a691a5dd425f08e5d9c1a

**Comment by tazjin** [comment]
Hey,

there is now a repeatable and reproducible build procedure (see recent commits to master and docs update).

I've made a signed binary release of a release candidate for the first version: [v0.1-rc1](https://github.com/tazjin/terraform-provider-keycloak/releases/tag/v0.1-rc1)

This version is pinned against Terraform `v0.10.0`, it may work with newer versions, too, once they are released (I'd assume minor versions at least).

While testing this on the most recent Keycloak version most things worked fine, but realm creation seems to have some strange side effect. I'll investigate that before making a "stable" release.

**Comment by sharebear** [comment]
Thanks, I just tested the rc build now using the configuration steps in the updated README and all looks good.

I've not verified the realm creation issue, will ask someone to verify that.
