### ISSUE TITLE
Support for adding roles

### ISSUE THREAD

**Issue by sideisra** [tazjin/terraform-provider-keycloak#27]
It would be great to be able to create roles within a realm.

**Comment by mahpatil** [comment]
@sideisra Looking at the keycloak API, cant really see a way to add a role without the client. Haven't tried the API myself. 
https://www.keycloak.org/docs-api/2.5/rest-api/index.html#_create_a_new_role_for_the_realm_or_client

**Comment by sideisra** [comment]
In the API doc is a second "Create a new role for the realm or client": https://www.keycloak.org/docs-api/2.5/rest-api/index.html#_create_a_new_role_for_the_realm_or_client_2
This should create realm level roles.

**Comment by mahpatil** [comment]
okay great. I will give it a shot when i have some spare time. you are welcome to fork and raise a PR as well. This will require a new resource under provider and a corresponding API handler

**Comment by phillipj** [comment]
It sounds to me like https://github.com/tazjin/terraform-provider-keycloak/pull/31 solves what you're looking for?

**Comment by phillipj** [comment]
Closing this as I think what got merged with #31 is what you're asking for. Don't hesitate to re-open if I'm wrong.
