### ISSUE TITLE
Specifying groups per user

### ISSUE THREAD

**Issue by phillipj** [tazjin/terraform-provider-keycloak#30]
Currently it looks like the way groups are assigned per user, is to defined *one* `keycloak_user_group_mapping` that has a list of all the user IDs in `user_ids`.

Looking at the Keycloak REST API docs, group memberships are created by requesting this endpoint: `PUT /{realm}/users/{id}/groups/{groupId}`. For ref this is also the endpoint we're already using in this project.

That endpoint gives an impression that group memberships are relative to a particular user. That's quite different from the mentioned `keycloak_user_group_mapping` which seems to be modelled around one group having its members declared to it.

@mahpatil have I completely misunderstood the intention of `keycloak_user_group_mapping`? If not, did you consider an user -> group membership where a `keycloak_user` has a `groups` field or similar?

**Comment by mahpatil** [comment]
Fair question, from my previous research the only way to assign users to a group was that API. However, I wanted the ability to assign multiple users in a single resource, rather than creating multiple resources. In our usage, we have a predefined set of groups and we wanted to assign multiple users to it, unfortunately, I couldn't find a corresponding Keycloak API. We could potentially rename the resource if it is confusing, or improve the documentation as part of this issue to make it clear.

**Comment by phillipj** [comment]
Thanks for elaborating!

Got any thoughts on supporting both models? Meaning being able to (1) assign a list of users to a group as today and (2) assign a list of groups to a user? The latter either in a new field directly onto `keycloak_user` or a new resource type..

Or would having those two be very weird?

**Comment by tazjin** [comment]
> Got any thoughts on supporting both models? Meaning being able to (1) assign a list of users to a group as today and (2) assign a list of groups to a user?

In other Terraform providers this is commonly handled by having two separate resources (sometimes with the problem that they conflict with each other). Check out the docs on [google_project_iam](https://www.terraform.io/docs/providers/google/r/google_project_iam.html) for example.

**Comment by phillipj** [comment]
Thanks for chiming in @tazjin! To me that's a confirmation that others has also realised that enforcing one way of modelling things isn't always ideal.

I'll close this issue for now since I've gotten the input I was looking for. If we decide to use groups in Keycloak more extensively, I'll probably end up adding a second way of modelling group memberships per user.
